version: '2.4'
services:
  db:
    image: postgres
    container_name: postgres-spring
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - devdojo_spring_data:/var/lib/postgres

volumes:
  devdojo_spring_data: